# Postmodeling Configuration File
#
# - "metrics" contain all the modeling parameters 
#   passed to the postmodeling functions.
# - "aesthetics" contain all ploting parameters 
#   passed to the ploting methods in postmodeling.
#
  path: '../../../../../../triage_output/output/matrices/'
  model_group_id: 
        - 19 
        - 43
        - 55

  thresholds: 
        rank_abs: [10, 20, 50]
        rank_pct: []
        
  max_depth_error_tree: 5
  n_features_plots: 10
  feature_groups: 
        - 'entity_id' 
        - 'zip_code' 
        - 'facility_type'

  figsize: [12,12]
  fontsize: 20
      
