# Postmodeling Configuration File
#
# - "metrics" contain all the modeling parameters 
#   passed to the postmodeling functions.
# - "aesthetics" contain all ploting parameters 
#   passed to the ploting methods in postmodeling.
#
  project_path: '../../../../../../triage_output/output/'
  model_group_id: 
        - 19 
        - 43
        - 55

  thresholds: 
        rank_abs: [10, 20, 50]
        rank_pct: [10, 20, 50]
  
  baseline_query: |
      SELECT g.model_group_id,
             m.model_id,
             EXTRACT('YEAR' FROM m.evaluation_end_time) AS as_of_date_year,
             m.metric,
             m.parameter,
             m.value,
             m.num_labeled_examples,
             m.num_labeled_above_threshold,
             m.num_positive_labels
       FROM test_results.evaluations m
       LEFT JOIN model_metadata.models g
       USING(model_id)
       WHERE g.model_group_id IN (1)
  
  max_depth_error_tree: 5
  n_features_plots: 10
  figsize: [12, 12]
  fontsize: 20
