# Thresholds for positive class (absolutes top k and top k %)
score_thresholds:
    rank_abs: [29896, 65194]
#    rank_pct: [1.0, 2.0, 5.0, 10.0 ]


#available options: "predefined", "majority" and "min_metric"
ref_groups_method: "min_metric"
# if "predefined" is selected, you need to provide the column:value pairs to be used as reference
#ref_groups:
  #"attribute_1": "<0.30"

# fairness threshold to be used for assessing fairness
fairness_threshold: 0.8


model_group_id: [] #if empty assumes all
train_end_time: [] #if empty assumes all

# the input query for attributes that will define the protected groups to run the bias audit on
# needs to return **entity_id** and optionally **as_of_date** to be joined with predictions
attributes_query: |
            select entity_id,
                   race,
                   gender,
                   case when age < 40 then '<40'
                         when age < 71 '40-70'
                         when age > 70 then '>70'
                        end as age_category
            from demographic_table

join_predictions_using: ['entity_id']
