dist: xenial
language: python
python: ["3.6", "3.7"]
addons:
  postgresql: '9.5'
services:
- postgresql
before_install:
- sudo apt-get update
- sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
install:
- pip install -r requirement/include/build.txt -r requirement/include/test-management.txt
env:
  matrix:
    - BOTO_CONFIG=/tmp/nowhere
  global:
    secure: U00z8IVLCenhcgaf2k+orF2zrNuQDbuSZs7ob+HvUPUHbFf8nadGN7RQ1E/AeiDPuqqOB03gQnqEEM1/o6EzzTGICsjUuSwGkmXXVwkpk5DZeEv6zIlrXpIaPvD0ZRTDh9g2GohmL4AEc7v7cKxMCSW2zYfP9qhiHMmxD98yB3llc3Z/zBjCC1Wp9d6/2+MEiUWytqYg1pI4vamL+awHrgjpImrMYnC4guMpvwHqslL1t/HhvHzzrob1EjxIPZuDzzSmXAcRTDkrX56gFKn6+wPyGf7M8BbiyilqFThN93hhNc3XYXTV+ptQgi6Rn8EfKpKuL0qBW3wOw9e6SExtz8ESNB+DjSe7zTPNXGH1WbeyMUCrArdZj0+FVCjoT8dG9bDUMl+kgMn2J5VBS4umpmIVaJCJvmldojax4W+fuR4nrfnb3pIP+hDjemlgbpdmjBh39c+A3ZC7Zcv3fhpvGIyg8/2GBzNRaNc4wiVcd8An+VlToJLLwuBekA0J1NDWvKmuMX5Kew+Y4w1w1WgJAW8kWMEY51tlIwuWYdsdIRGLFgOucbtLMJpQXjtP8OxKHcWsCDiIEZJk49IMdcU3q6Wmss1TfElNwxpdpECrLEn8y1CDIhzb+PcUYdqHWPgW30TKOs4URags4m/XVmDJZrgv3JcwiQiYbUepZ8hPdTY=
script: tox
notifications:
  email: false
after_success: codecov
deploy:
  -
    repo: dssg/triage
    distributions: sdist bdist_wheel
    password:
      secure: o0JpnmjqbYgu75eUXfxX/FUw0ek6Pp1bdhqRH4x3VnINy3TdBZ1tdD35B0l8L5UaR+j8LawOwTt3md3EyQTNpJQypFChcF6LDTS2hF0ZxyFphgWWo+DWhx8abAT/xAECO7Z7pjynQcYy1OAC3U+V8E7gevlr/nWD1/Le0mC+BJocJQ6QBZCD84E4ennXdLUgMqQZlCUKvi6j7EXvV4NoXbuZPaZKhC77CZ0xpEu0aQG9IPPGgkmL3a5RQd5/Uu8rlBES5lzh9bysW3NvXSUaq5XXrQAx5Fba3/lDN8aVkFvseLwOfjZ1pdTnbcDH5ti24YYecBsRsF4qmOY5pVZQZWeQRZFZ+/wp0fa34M9XjIyN7rXKyPm2UX7A8IYyF95xvniKs0qUOBXGRq5IFse6OSUIuKLYl3XjN3IPUPRCXnxoCXyRFV3NNyvtfb47+eejrgfqav9SKE5auA/t5ioQh6FuVqBMCWK7FFiZCt4z1g6RmYAFlRcTuHeedKjOfzWU79AeUoTJA1tfz4FtNjIWfoZJyCNCUCQjYzD/yCJGuDCuY/42+QGaMo9oEVgw7ublC0Xzib+zyuogTvjxYQR+XGJnCgeDYEs7A/o8CHdJKSeIbxpnuZShPpkdBQgzWmnvlfgJTYICaa10oAf5+sDnBQQsumZBT3iuKJETXIkNxeo=
    provider: pypi
    user: dssg
    on:
       repo: dssg/triage
       tags: true
  -
    provider: script
    script: manage docsdeploy
    on:
      tags: true
